import Config

# Configure your database
config :fin_deploy, FinDeploy.Repo,
  username: "admin",
  password: "admin",
  hostname: "localhost",
  database: "findeploychat",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10


config :fin_deploy, FinDeploy.Repo.Citus,
  username: "admin",
  password: "admin",
  hostname: "localhost",
  database: "findeploychat",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :fin_deploy,
  env: :prod

config :fin_deploy, ecto_repos: [
  Workcake.Repo,
  Workcake.Repo.Citus
]

config :fin_deploy, FinDeployWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [port: 4000],
  url: [host: "103.200.20.242"],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "v1FBPk5Sfju7hU6l5J9vB33w95JFQSMeL1t3USfefIPNAoBcF/JAujoWnnQpmJbK",
  watchers: []

config :logger, level: :warn
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :fin_deploy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
